spring:
  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: geri
    password: adm1n
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA properties
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
# Server configuration
server:
  port: 8080

